# Copyright 2025 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

---
name: OSPS Compliance

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  attest:
    permissions:
      id-token: write # needed for keyless signing
      contents: read
      actions: read # needed to download the SLSA source provenance
    uses: carabiner-labs/actions/.github/workflows/osps-compliance.yaml@f4252411b8f59d3e74b708c9943d32786130d1b1 # main
    with:
      branch: main
      slsa-source-workflow: SLSA Source

  push:
    needs: attest
    permissions:
      attestations: write # needed to push the attestations to the GitHub store
    uses: carabiner-labs/actions/.github/workflows/push-attestations.yaml@f4252411b8f59d3e74b708c9943d32786130d1b1 # main
