# Copyright 2025 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

---
name: OSPS Compliance

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  attest:
    permissions:
      id-token: write # needed for keyless signing
      contents: read
      actions: read # needed to download the SLSA source provenance
      attestations: write # needed to push the attestations to the GitHub store
    uses: carabiner-labs/actions/.github/workflows/osps-compliance.yaml@f00eee36c5ab0f7b27169e4d21330600948046a8 # main
    with:
      branch: main
      slsa-source-workflow: SLSA Source
      push-attestations: true
