# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

---
name: verify

on:
  push:
    branches:
      - "main"
  pull_request:

permissions: {}

jobs:
  resolve-versions:
    name: resolve go versions
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      GO_MINOR_VERSION_STABLE: ${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Resolve Go versions
        id: versions
        uses: carabiner-dev/actions/go/versions@36a39ef667efe7112df8b1a534a4e37f35fad6fd

  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    needs: resolve-versions

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ needs.resolve-versions.outputs.GO_MINOR_VERSION_STABLE }}
          check-latest: true
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.11
